#!/usr/bin/env bash
# (c) 2019 containerenv authors
#
# Thin wrapper to download init scripts

output() {
  echo "[$(date '+%m/%d/%Y %H:%M:%S')] $*"
}

failed_to_download() {
  output "Warning: Failed to pull the latest init script down"

  # use a previous version that commit most likely stored.
  if [[ ! -e "/init" ]]; then
    output "Error: no previous init version found, unable to start."
    exit 1
  fi
}

output "pulling latest init script from the internet ..."
git clone --depth=1 https://github.com/containerenv/init /init || failed_to_download
output "wrapping init"

exec /init/init "$*"